on:
  push:
    branches:
      - main

name: Release

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Packages
        run: npm install
      - name: Build Extension
        run: npm run build:ci
      - name: Release to Github / NPM
        run: npm run release:ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
